name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Check folder
      run: pwd
    - name: Check files
      run: ls -ltr
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: test API with curl command
      run: curl -X 'GET' 'http://${{steps.ip.outputs.ipv4}}:3000/api' 
    - name: test Front End with curl command
      run: curl -X 'GET' 'http://${{steps.ip.outputs.ipv4}}:4200' 
