name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the stack
      run: docker-compose -f docker-compose.yml up -d
    - name: Check folder
      run: pwd
    - name: Check files
      run: ls -ltr
    - name: test API with ping command
      run: ping –c 5 http://localhost:3000/api
    - name: test Front End with ping command
      run: ping –c 5 http://localhost:4200
